/**
 * Tactical Infinity adapter for shared camp/RTS building SSOT.
 * Prefer these helpers in new build UI; legacy registries stay for mesh loaders.
 */
export {
  MASTER_BUILDINGS,
  MASTER_UNITS,
  ITEM_RECIPES,
  TURRET_PROFILES,
  DEFAULT_DEFENSE_BRAIN,
  getBuilding,
  getUnit,
  getRecipe,
  buildingsForTab,
  buildingsForFaction,
  buildingPaletteRows,
  canAfford,
  canAfford as canAffordSsot,
  spendCost,
  recipesForBuilding,
  unitsTrainedAt,
  enqueueItemJob,
  enqueueUnitJob,
  enqueueVehicleJob,
  tickProduction,
  jobProgress01,
  pickBestThreat,
  tickDefenderBehavior,
  leadTargetPoint,
  inClaimBuildRadius,
  resolveBuilding,
  toTiCost,
  // claim + train
  getClaim,
  plantClaimFlag,
  clearClaim,
  loadClaimFromStorage,
  validateBuildAt,
  registerPlacedOnClaim,
  persistClaimToApi,
  queueTrainUnit,
  queueCraftItem,
  getJobsForBuilding,
  tickTrainQueue,
  describeJob,
  subscribeClaim,
  subscribeTrain,
  type BuildingCatalogEntry,
  type UnitCatalogEntry,
  type ResourceCost,
  type ClaimFlagState,
  type ProductionJob,
  type AllyBehavior,
  type DefenseBrainConfig,
  PIRATE_PACK_CDN,
  PIRATE_MESH,
  PIRATE_PACK_CATALOG,
  rollBuriedTreasure,
  getPirateEntry,
} from "../../../shared/camp";
