/**
 * infoHubAPI.ts — canonical Grudge Land data hub client.
 *
 * `info.grudge-studio.com` is the source-of-truth Game Data Hub shared by
 * every Grudge Land title. All canonical datasets (professions, skill trees,
 * weapons, items, recipes, armour, attributes, etc.) live there as static
 * JSON under `/data/master-*.json`, regenerated by the studio's data
 * pipeline. By pulling from the hub at runtime, every Grudge Land game
 * stays in lock-step with the canonical balance pass without a redeploy.
 *
 * Two-layer cache:
 *   1. in-memory (per tab session) — instant repeat reads.
 *   2. sessionStorage — survives soft navigations within a tab.
 *
 * Datasets are versioned (`version` + `generated` fields). The cache key
 * is dataset name only; callers that want a force-refresh can call
 * `clearInfoHubCache()` or pass `{ force: true }`.
 *
 * This module is intentionally dependency-free: usable from React via
 * tanstack-query, from plain hooks, or from server code (works under
 * Node 18+ with global fetch).
 */

export const INFO_HUB_BASE = 'https://info.grudge-studio.com';
export const INFO_HUB_DATA = `${INFO_HUB_BASE}/data`;

/** Datasets exposed by the hub. */
export type InfoHubDataset =
  | 'professions'
  | 'weaponSkills'
  | 'skillTrees'
  | 'weapons'
  | 'armor'
  | 'materials'
  | 'consumables'
  | 'recipes'
  | 'items'
  | 'attributes'
  | 'artifacts'
  | 'registry';

const FILENAME: Record<InfoHubDataset, string> = {
  professions:  'master-professions.json',
  weaponSkills: 'master-weaponSkills.json',
  skillTrees:   'master-skillTrees.json',
  weapons:      'master-weapons.json',
  armor:        'master-armor.json',
  materials:    'master-materials.json',
  consumables:  'master-consumables.json',
  recipes:      'master-recipes.json',
  items:        'master-items.json',
  attributes:   'master-attributes.json',
  artifacts:    'master-artifacts.json',
  registry:     'master-registry.json',
};

// ── Type shapes for the datasets we actively consume ─────────────────────────
// The hub also returns extra fields; we only narrow the parts the game uses.
// Use `getDatasetRaw()` if you need the unmodelled trail.

export interface CanonicalProfessions {
  version: string;
  generated: string;
  totalGathering: number;
  totalCrafting: number;
  totalNodes: number;
  gathering: Record<string, GatheringDef>;
  crafting:  Record<string, CraftingDef>;
  gatheringMilestones: ProfessionMilestone[];
  xpTable: Record<string, number>;
  tierNames:  string[];
  tierColors: Record<string, string>;
}

export interface GatheringDef {
  uuid: string;
  name: string;
  category: 'gathering';
  icon: string;
  color: string;
  resources: string[];
  tierResources: Record<string, string[]>;
  feedsInto: string[];
}

export interface CraftingDef {
  uuid: string;
  name: string;
  category: 'crafting';
  icon: string;
  color: string;
  tools?: string[];
  primaryOutputs?: string[];
  feedsFrom?: string[];
  skillTree?: unknown;
}

export interface ProfessionMilestone {
  level: number;
  unlock: string;
  description: string;
}

export interface CanonicalWeaponSkills {
  version: string;
  totalWeaponTypes: number;
  totalSkills: number;
  classRestrictions: Record<string, string[]>;
  weaponTypes: Array<{
    id: string;
    name: string;
    icon: string;
    classes: string[];
    totalSkills: number;
    skills?: unknown[];
  }>;
}

// ── Cache ────────────────────────────────────────────────────────────────────

const memCache = new Map<InfoHubDataset, unknown>();
const inflight = new Map<InfoHubDataset, Promise<unknown>>();
const STORAGE_PREFIX = 'grudge_hub_';

function readSession<T>(key: InfoHubDataset): T | null {
  if (typeof window === 'undefined') return null;
  try {
    const raw = window.sessionStorage.getItem(STORAGE_PREFIX + key);
    return raw ? (JSON.parse(raw) as T) : null;
  } catch {
    return null;
  }
}

function writeSession<T>(key: InfoHubDataset, value: T): void {
  if (typeof window === 'undefined') return;
  try {
    window.sessionStorage.setItem(STORAGE_PREFIX + key, JSON.stringify(value));
  } catch {
    /* quota or disabled — fine, in-memory still works */
  }
}

export function clearInfoHubCache(key?: InfoHubDataset): void {
  if (key) {
    memCache.delete(key);
    if (typeof window !== 'undefined') {
      try { window.sessionStorage.removeItem(STORAGE_PREFIX + key); } catch { /* ignore */ }
    }
    return;
  }
  memCache.clear();
  if (typeof window !== 'undefined') {
    try {
      for (const k of Object.keys(window.sessionStorage)) {
        if (k.startsWith(STORAGE_PREFIX)) window.sessionStorage.removeItem(k);
      }
    } catch { /* ignore */ }
  }
}

// ── Fetch ────────────────────────────────────────────────────────────────────

interface FetchOpts {
  /** Skip caches and re-fetch from the hub. */
  force?: boolean;
  /** Abort signal for the underlying fetch. */
  signal?: AbortSignal;
}

async function getDatasetRaw<T>(key: InfoHubDataset, opts: FetchOpts = {}): Promise<T> {
  if (!opts.force) {
    const m = memCache.get(key) as T | undefined;
    if (m) return m;
    const s = readSession<T>(key);
    if (s) {
      memCache.set(key, s);
      return s;
    }
  }
  const existing = inflight.get(key) as Promise<T> | undefined;
  if (existing && !opts.force) return existing;

  const url = `${INFO_HUB_DATA}/${FILENAME[key]}`;
  const promise = fetch(url, { signal: opts.signal })
    .then((r) => {
      if (!r.ok) throw new Error(`InfoHub ${key} HTTP ${r.status}`);
      return r.json() as Promise<T>;
    })
    .then((data) => {
      memCache.set(key, data);
      writeSession(key, data);
      return data;
    })
    .finally(() => {
      inflight.delete(key);
    });

  inflight.set(key, promise);
  return promise;
}

// ── Public API ───────────────────────────────────────────────────────────────

export const InfoHub = {
  /** Canonical 6 gathering + 5 crafting professions, 21 milestones, XP table. */
  getProfessions: (opts?: FetchOpts) =>
    getDatasetRaw<CanonicalProfessions>('professions', opts),

  /** 17 weapon types × class restrictions × per-type skill arsenals. */
  getWeaponSkills: (opts?: FetchOpts) =>
    getDatasetRaw<CanonicalWeaponSkills>('weaponSkills', opts),

  /** Class skill trees (Warrior / Mage / Ranger / Worge). */
  getSkillTrees:  (opts?: FetchOpts) => getDatasetRaw<unknown>('skillTrees',  opts),

  /** Tiered weapon catalogue. */
  getWeapons:     (opts?: FetchOpts) => getDatasetRaw<unknown>('weapons',     opts),
  getArmor:       (opts?: FetchOpts) => getDatasetRaw<unknown>('armor',       opts),
  getMaterials:   (opts?: FetchOpts) => getDatasetRaw<unknown>('materials',   opts),
  getConsumables: (opts?: FetchOpts) => getDatasetRaw<unknown>('consumables', opts),
  getRecipes:     (opts?: FetchOpts) => getDatasetRaw<unknown>('recipes',     opts),
  getItems:       (opts?: FetchOpts) => getDatasetRaw<unknown>('items',       opts),
  getAttributes:  (opts?: FetchOpts) => getDatasetRaw<unknown>('attributes',  opts),
  getArtifacts:   (opts?: FetchOpts) => getDatasetRaw<unknown>('artifacts',   opts),
  getRegistry:    (opts?: FetchOpts) => getDatasetRaw<unknown>('registry',    opts),

  /** Escape hatch: fetch any dataset by key. */
  getDataset: getDatasetRaw,
} as const;

// ── React-friendly helpers ───────────────────────────────────────────────────

/**
 * Build a stable @tanstack/react-query key for a hub dataset.
 *
 * Usage:
 *   const { data } = useQuery({
 *     queryKey: infoHubQueryKey('professions'),
 *     queryFn: () => InfoHub.getProfessions(),
 *     staleTime: 1000 * 60 * 60, // hub regenerates infrequently
 *   });
 */
export function infoHubQueryKey(dataset: InfoHubDataset): readonly [string, InfoHubDataset] {
  return ['/info-hub', dataset] as const;
}
